### ISSUE TITLE
Add cellsVisualizationSpacingMultipler attributes to netpyne.metadata

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#255]
Parameter defined in Netpyne-UI: https://github.com/MetaCell/NetPyNE-UI/blob/fb4faa84045e8fba0a1858c9bead2194da39565a/netpyne_ui/netpyne_geppetto.py#L45

These weren't yet added to netpyne.metadata, currently we dynamically extend it 

But that is likely to cause some issues, one I stumbled upon when I start with an empty project and export model to Python, I get an exception thrown by netpyne (see screen attached)

![Bildschirmfoto 2021-04-09 um 11.53.58.png](https://images.zenhubusercontent.com/600fdb37a2c5e223bc039639/ac8fc703-9f04-45fe-909d-9b103975377e)

**Comment by salvadord** [comment]
Added this property to netParams.py and to metadata.py. However, I made it a single list variable instead of 3 separate ones ... since this is an ugly ad hoc feature, that pollutes the code and should be eventually removed ;) :

https://github.com/Neurosim-lab/netpyne/commit/bbc45ddf018856192645594f8a646281ec5821f2

I also update the netpyne_workspace hnn examples accordingly:

https://github.com/Neurosim-lab/netpyne_workspace/commit/f1d5dac95ab6c4a2868f072490b239bb1842d789

This will require the netpyne_UI side to be updated to use a list variable, instead of 3 variables. I assume it will be straight forward, but if too much complication, let me know and I'll separate into 3 variables again.

**Comment by lrebscher** [comment]
It's surprisingly not straightforward if we want to provide a field that has robust input validation :D

Currently, we don't have much freedom in the way frontend input maps to netpyne fields, the current synchronization mechanism is very opinionated and coupled to how an input field must look like. We only support a range of different input types and for everything else we have to do some custom handling.

Out of the box, we could just use one field and let the user set a value "[1,2,4]" but that's not a user friendly way to enter input, also it requires some custom rules to verify input

My suggestion would be to keep the three variables and find out how we can remove it completely

Usually this wouldn't be a problem. I could just create three explicit fields in the frontend and update only a specific index in the list in simConfig, but that's not so easy with the current impl we have here.

**Comment by lrebscher** [comment]
@salvadord the issue here is that we use the same label for each field so we have "Cells visualization spacing multiplier (X, Y, Z)" for each field. To make it simple I would suggest to go with my previous suggestion and stick with the three explicit attributes

**Comment by salvadord** [comment]
Can we just remove this from the GUI frontend? I know it's used in the HNN example, but the value is already set in the script/code, and doesn't need to be modified by the user; nor will it be used by any other model. So the netParams.cellsVisualizationSpacingMultiplier can just be used in the GUI backend, but doesn't really need to be editable.

**Comment by lrebscher** [comment]
Makes sense, I removed it :)
