### ISSUE TITLE
NetPyNe rxd code incompatible with NEURON 8.x.x. 

### ISSUE THREAD

**Issue by lrebscher** [MetaCell/NetPyNE-UI#359]
**Reproduction:**

- import Tut 3a
- create network

Only happens if you create network, not when you create and simulate.

Was introduced by recent upgrade of NEURON 7.x.x. to 8.x.x

<img width="1059" alt="Bildschirmfoto 2021-07-05 um 18 07 37" src="https://user-images.githubusercontent.com/7281685/124498053-11f82f80-ddbc-11eb-89bb-99f712f60d84.png">

**Comment by salvadord** [comment]
Will look into this. As a side note when you "create" and then "simulate", in the "simulate" step it was actually creating again. So the error seems to be due to trying to create the network twice.

**Comment by urdapile** [comment]
Issue 359 NetPyNE-UI // NetPyNe rxd code incompatible with NEURON 8.x.x.

Description of the problem
-Load Tut 3a en NetPyNE GUI
-Create Network
-Launch simulation (re create the network, according to Salvador's comments). It crashes.

Outside the GUI, we have the same issue if, from the rxd_net example, we call:
1) Getting all
from netpyne import sim
from netParams import netParams
from cfg import cfg

2) Creating the network 
sim.create(netParams, cfg)

3) Re-creating the network
Either with sim.create(netParams, cfg) or sim.createSimulate(netParams, cfg), which I think is what the GUI does.

This DOES NOT happen if we call sim.createSimulate(netParams, cfg) twice, in cascade.


After trying different configurations in the model, looking into the code, etc, I think the following is happening: 

1) The LFP recording sets a pointer to a current (in particular to a Ca-current). If we disable everything related to LFP, everything goes smooth.
2) If keeping the LFP, we omit the extracellular space (here currents flow through the membrane and classical NEURON interacts with RxD), everything goes smooth. In this case, RxD sets a lot of stuff (global variables, pointers, etc). The pointers to the Ca-current (from the LFP and from the extracellular space) seem to be the origin of the conflict.

3) When calling createSimulate, after simulating, the method calls "gatherData", where after collecting all the data, the pointer used in the LFP is released. If the do: create + gatherData + create, it works. In particular, we can comment all the code and leave only the part that NetPyNE releases the pointer and everything works fine.

4) Also, we can call a method already implemented in NetPyNE, sim.clearAll(), where all the structure in sim.net is deleted and pointers released. The only thing is that in this method we have to minimally change one part because it gives an error when called after sim.create. I suppose it was designed to be called after simulate (and, in this case, sim.net has other things to delete). So, in my opinion, the cleanest way to proceed is:
1) create
2) sim.clearAll(), slightly modified, + createSimulate, all in the same call (press the rocket). If this is how the GUI works when launching the simulation.

Of course, with this procedure, all information modified in "net.sim" from command line after creating the network (instead of modifying the netParams dictionary) will be lost during the clearAll.
