### ISSUE TITLE
After trying to import a cell file browser is inside /mod folder and can't go back

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#48]
Using Docker in Mac OS, I tried to import PTcell.hoc, set the mod folder and selected 'compile mod'.
The import didn't work, and when I tried to import cell again, the folder was inside the /mod folder and couldn't go back.

![image](https://user-images.githubusercontent.com/8440562/42285526-de747212-7f7d-11e8-9a72-b31b7942fbbf.png)

**Comment by adrianq** [comment]
@salvadord this is something I mentioned in the meeting. It is solved in this https://github.com/MetaCell/NetPyNE-UI/pull/35/commits/723388c28a75beadc8b023019290d991574cab18 that is already in development. Why don't you try to use your local repos instead of the docker image at least until the new docker is released?

**Comment by salvadord** [comment]
@adrianq - ah ok, sounded familiar :) ... yeah ok, just used the docker to try fix the h.load_file() thing, thanks
