### ISSUE TITLE
Disable sentry when is not a production build

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#480]
I built the development branch and managed to get it running locally, but there seems to be a lot of communication to a remote instance of sentry (for logging):

```
https://sentry.metacell.us:443 "POST /api/6/envelope/ HTTP/1.1" 200 41
https://sentry.metacell.us:443 "POST /api/6/envelope/ HTTP/1.1" 200 41
https://sentry.metacell.us:443 "POST /api/6/store/ HTTP/1.1" 200 41
...
```
Is this required/desirable?

**Comment by ddelpiano** [comment]
disable sentry when working in a "not production" build. @enicolasgomez

**Comment by enicolasgomez** [comment]
@pgleeson having a hard time to undertand what is firing this error logs due to the injectional nature of sentry plugin but just to be clear, does this represent what you are reporting? or is it something else?

![Screen Shot 2022-11-09 at 18.58.14.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/5a7b1d46-ff47-4f8e-b60f-eb9a52bd8456)

**Comment by enicolasgomez** [comment]
@ddelpiano PR ready:
https://github.com/MetaCell/NetPyNE-UI/pull/589

**Comment by pgleeson** [comment]
@enicolasgomez I believe so, yes. Basically if someone installs this as a standalone application, it will seem very strange that it needs to communicate in any way with MetaCell. It also fills up the logs...
