### ISSUE TITLE
Issue with utils.convertToJS (from geppetto-meta?)

### ISSUE THREAD

**Issue by pgleeson** [MetaCell/NetPyNE-UI#499]
Still having an issue with this error when loading JSON:
<img width="1350" alt="Screenshot 2022-04-12 at 10 57 53" src="https://user-images.githubusercontent.com/1556687/162934834-636b258b-f6a0-4ade-8822-55ef06d15a39.png">
so moving this to top level issue (previously reported [here](https://github.com/MetaCell/NetPyNE-UI/issues/213#issuecomment-1088546414))

Or should this be an issue in geppetto-meta @ddelpiano @enicolasgomez?

**Comment by ddelpiano** [comment]
@pgleeson I tried with the latest and I am not able to reproduce the problem you are reporting.

The simulation it seems succeeded since I can plot the data from the model, however the 3d representation is still broken. This will require further investigation but I am not sure we have the bandwidth to allocate this at the moment. 
Let's discuss it at the sprint meeting.

![scrnli_20_04_2022_13-29-56](https://user-images.githubusercontent.com/37704177/164221529-ba236fe8-2c42-4c01-92b5-6537df3aeb2f.png)

**Comment by pgleeson** [comment]
Great, thanks for checking @ddelpiano. I assume https://github.com/MetaCell/NetPyNE-UI/tree/feature/499 is the branch I can try for this locally?

**Comment by salvadord** [comment]
happened also to me running simple batch of tut1:
![image](https://user-images.githubusercontent.com/8440562/170378827-194af731-5ad7-443f-8f52-7503fac066b3.png)
