### ISSUE TITLE
Experiment manager missing netParams.connParams parameters in 'parameter' dropdown

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#522]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/8440562/169620895-c7eebdd1-f387-4ad9-bf8c-027bb3c4d1d9.png">

**Comment by filippomc** [comment]
@salvadord connParams are missing because the logic needs metadata field types to be specified here: https://github.com/suny-downstate-medical-center/netpyne/blob/db0103a44c3d52dd8f043b1703618c1f8c806033/netpyne/metadata/metadata.py#L595; at the moment we can only support fields of types int, float, bool, str, while they are not either not specified or of not supported types in that list

**Comment by filippomc** [comment]
I'm experimenting on supporting fields defining as "func" type, so allowing for a function specifier. Is it appropriate to say that function fields are equivalent to float fields in the batch context? Or there are cases where functions can return a string? @salvadord @ddelpiano

**Comment by salvadord** [comment]
That's correct, "func"felds should be floats within the batch. thanks
