### ISSUE TITLE
Bokeh plots rescaling

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#552]
Seems like the bokeh plots could be rescaled more so it's possible to visualize raster plots and voltage traces without having to scroll. I think these was working ok in previous versions. @ddelpiano @tarelli

**Comment by enicolasgomez** [comment]
@ddelpiano if you look at the commit:

https://github.com/MetaCell/NetPyNE-UI/commit/8b02f7835337fe155f6053d5107616ccd68a07b3

I attempted to place the overflow:hidden property by setting it to the iframe property, which didn't work as that's the iframe containing the actual HTML from the plot.

After realizing that I attempted to extend the already existing response injector on the plotMiddleware again without success (couldn't also verify that the inject is actually having any effect).

Also, as this issue is affecting the navigation menu, we should think about changing this at a menuConfiguration level ( e.g. widget scroll = no ) and maybe extend the layout mechanism to consider this.

**Comment by ddelpiano** [comment]
Hi @enicolasgomez , could you try installing netpyne in development mode and applying the change to see if locally makes a difference for you? 
If that works feel free to open a PR on the netpyne repository, I will test your branch once there is a PR.

thanks!

**Comment by enicolasgomez** [comment]
@ddelpiano ended up fixing it by changing the overflow property on the iPlot javascript file, the iframe seems to override with the given values so no need to change the lib.

**Comment by ddelpiano** [comment]
@enicolasgomez moving this back to 'in progress' after functional testing.

Check the screenshots below, on localhost I am running your branch where in staging we are running development (last build 8 days ago 

![scrnli_30_11_2022_13-17-51.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/16bdbda0-baf5-42dd-8f05-099f8d48ba9b)

![scrnli_30_11_2022_13-17-53.png](https://images.zenhubusercontent.com/5b0293e84b5806bc2bd3f170/74cd1478-9894-4ac5-a428-eaba50052b29)

**Comment by enicolasgomez** [comment]
@salvadord @ddelpiano Pushed a fix in the bokeh plot styling processor. I could test that this was not originated by my changes as the styling which caused this came from the bokeh rendering (maybe a version upgrade while we were working on it?). Anyway, managed to catch and fix to fit our layout.
