### ISSUE TITLE
Open new netpyne model format to be intergrated with the GUI

### ISSUE THREAD

**Issue by ddelpiano** [MetaCell/NetPyNE-UI#609]

**Comment by salvadord** [comment]
@vvbragin can you please have a look at this?

**Comment by vvbragin** [comment]
Please use this branch https://github.com/suny-downstate-medical-center/netpyne/tree/file-format
(it's already up-to-date with current `development`)
The API for loading is `cfg, netParams = sim.loadFromIndexFile('index.npjson')`
I haven't yet implemented the changes we discussed on our meeting, so currently the index file should be passed explicitly, and mod files doesn't get compiled automatically.
You can use it with most of examples in `examples` folder (just check that that concrete example contains index.json, which means that it is converted to new folder). For instance, `examples/HHTut` is converted. 
Please also note that the root dir of example should be set as current working directory, so that the API resolves the paths correctly.
I'm working on making it more flexible as we discussed, should be available early next week
@ddelpiano

**Comment by enicolasgomez** [comment]
@vvbragin @ddelpiano 
Quick question about `loadFromIndexFile`, so I'm passing the full path to the npindex file from the IDE and this is how the json.load looks like:

'simConfig_python':
'src/cfg.py'
..etc

but when the module attempts to load dynamically errors out a `FileNotFoundException` as src/cfg.py is relative to somewhere else.

I guess this is what you mean by "the root dir of example should be set as current working directory, so that the API resolves the paths correctly.". ?

![Screen Shot 2022-11-30 at 10.52.38.png](https://images.zenhubusercontent.com/610183f51ec1245011ca9923/53feb096-d947-49e7-920f-a801a9062850)

'src/init.py'
'netParams_python':
'src/netParams.py'

**Comment by vvbragin** [comment]
Hi @enicolasgomez, sorry for delay, I'm not getting any notifications from github for some reason - will try to fix that.

Anyway, I’ve just updated the API based on what we discussed on the meeting. The `loadFromIndexFile` is still there, but just serves as a wrapper, whereas the main API is now
`def loadModel(path, loadMechs=True, forceCompileMechs=False)`
It automatically handles path-related stuff, so there is no restrictions on current working dir any more.
The `path` argument can be either path to directory (in which case it will try to find default `index.npjson` there), or the path to the exact index-file.
Finally, by default it will compile and load mechanisms from mod.

**Comment by vvbragin** [comment]
Here is the proposal for model saving API:
`def saveModel(netParams, simConfig, srcPath, dstPath=None, exportNetParamsAsPython=False, exportSimConfigAsPython=False)`

- `netParams`, `simConfig` - python structures to be saved (i.e. netpyne.specs.NetParams and netpyne.specs.SimConfig objects)
- `srcPath` - path to original model (it's needed in addition to netParams and simConfig, in order to have reference to any other files in case model is to be duplicated at some other path)
- `dstPath` - where to save the model
- `exportNetParamsAsPython`/`exportSimConfigAsPython` - note that if it's set to `False` (default), netParams/cfg will be saved as JSON, even if in original model it was python. As we discussed, this is done to expose the fact that in case of saving as python, some of custom func-ty in original python files may be lost.

If no `dstPath` is provided (or if it coincides with `srcPath` - existing model dir) - the current model at srcPath will be overriden with new contents of `netParams` and `simConfig`.
Otherwise, the whole model dir from srcPath will be copied to dstPath, and `netParams` and `simConfig` will there replace original files.

For both `srcPath` and `dstPath` the following applies (as in case of `loadModel` API): if path is dir (not the exact .npjson file), it will presume `<path>/index.npjson` as default index file.

**Comment by vvbragin** [comment]
The API is available in branch https://github.com/suny-downstate-medical-center/netpyne/tree/save_model

Here are some examples of usage:
(`netParams` and `cfg` in all examples are python objects (`specs.NetParams` and `specs.SimConfig`)

To save model "from scratch" (e.g. with no other context except netParams and cfg objs):
```
sim.saveModel(netParams, cfg, srcPath=None, dstPath='path/to/dstFolder')
```
(as discussed, by default it creates netParams and cfg files in json-format. Use `exportNetParamsAsPython`/`exportSimConfigAsPython` to force-save as python. E.g:
```
sim.saveModel(netParams, cfg, srcPath=None, dstPath='path/to/dstFolder', exportNetParamsAsPython=True)
```
The code above will save model to `path/to/dstFolder` and by default create there `index.npjson`
To use custom index-file instead, it's name should be explicitly specified:
```
sim.saveModel(netParams, cfg, srcPath=None, dstPath='path/to/dstFolder/some-custom.npjson')
```
To duplicate already existing model (whole file structure) but override net params and cfg with what’s in `netParams` and `cfg` objects, specify that existing model srcPath :
```
sim.saveModel(netParams, cfg, srcPath=‘path/to/originalModel’, dstPath='path/to/dstFolder/some-custom.npjson’)
```
Again, this will by default try loading ‘path/to/originalModel/**index.npjson**`. If there is other index-file in this folder to load from, it should be specified explicitly in srcPath.

If dstPath is same as srcPath (equivalently, if dstPath is None), netParams and cfg will be overridden in-place.
If dstPath and srcPath are same folders, but index-files are different, netParams and cfg will be exported to this folder, and new index-file will be created in this folder (i.e. creating an additional ‘variant’ of same model)
E.g. this
```
sim.saveModel(netParams, cfg, srcPath='path/to/originalModel', dstPath='path/to/originalModel/variant2.npjson')
```
will result in creating in dir `path/to/originalModel` additional netParams and cfg files based on `netParams` and `cfg` objs, and the new `variant2.npjson` will be created, which will contain references to those new params and cfg.
