### ISSUE TITLE
Error in experiment (batch) simulations 

### ISSUE THREAD

**Issue by salvadord** [MetaCell/NetPyNE-UI#648]
I loaded tutorial 1 and set up an experiment (batch) with 4 values, and ran in "local" with 2 cores. The simulations did not complete. See screenshots below. 

<img width="1535" alt="image" src="https://user-images.githubusercontent.com/8440562/210908902-ffef9662-f8ba-4ea1-8753-55d801f73dec.png">

<img width="564" alt="image" src="https://user-images.githubusercontent.com/8440562/210909001-2bb5fba2-bde2-424a-9c95-0473a1c18534.png">

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/8440562/210908799-e1730ceb-6106-46ac-81b0-0b4f955e199b.png">

<img width="1459" alt="image" src="https://user-images.githubusercontent.com/8440562/210908814-a9f8356f-6517-489e-adcf-6ba66482d17e.png">

<img width="938" alt="image" src="https://user-images.githubusercontent.com/8440562/210908770-b0ecd243-ef0c-4f30-b7cf-f2343b7aca79.png">

<img width="1362" alt="image" src="https://user-images.githubusercontent.com/8440562/210908732-20f384db-f987-4faa-8803-4c53dfcbbe45.png">

**Comment by pgleeson** [comment]
@salvadord Has the batch/experiment functionality been tested much before on OSB2?

**Comment by ddelpiano** [comment]
@salvadord  @pgleeson it was, unfortunately we noticed a bug in the installation script recently (already fixed) that was allowing the installation to get the latest version of netpyne rather than the one specified in the requirements.txt.
Due to this OSB was running a specific version of the UI but with the latest netpyne, and the issue flagged for the experiment manager was sitting in netpyne (as already flagged and discussd in slack).
